Add contact form
netguru/fe-contact-form pull request #1
Opened 2019-09-29 16:33 UTC by Tomekmularczyk

2020-06-04 12:41 UTC, betafcc commented on src/Contact.js
> +    // console.log(this.state);
Clean useless comment

2020-11-19 14:02 UTC, blueturtle13g requested changes
please make the changes and request again

2020-11-19 14:02 UTC, blueturtle13g commented on src/Contact.js
> +          src="https://www.netguru.com/hubfs/images/landing_pages/og72x.png"
use constants for such strings

2020-11-19 14:02 UTC, blueturtle13g commented on src/Contact.js
> +        <div className="header">Contact</div>
use semantic html, not div for header

2020-11-19 14:02 UTC, blueturtle13g commented on src/Contact.js
> +        <div className="title">Use form below to contact us:</div>
don't use div for strings, instead use h tags

2020-11-19 14:02 UTC, blueturtle13g commented on src/App.js
>  function App() {
use arrow functions instead

2020-11-19 14:43 UTC, closed without merging